//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystaTaller.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class systa_tallerEntities : DbContext
    {
        public systa_tallerEntities()
            : base("name=systa_tallerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SYSTA_CLIENTES> SYSTA_CLIENTES { get; set; }
        public DbSet<SYSTA_MECANICO> SYSTA_MECANICO { get; set; }
        public DbSet<SYSTA_TALLER> SYSTA_TALLER { get; set; }
        public DbSet<SYSTA_USUARIO> SYSTA_USUARIO { get; set; }
        public DbSet<SYSTA_VEHICULO> SYSTA_VEHICULO { get; set; }
    }
}
