//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystaTaller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTAS_TALLER
    {
        public SYSTAS_TALLER()
        {
            this.SYSTAS_FACTURA = new HashSet<SYSTAS_FACTURA>();
        }
    
        public int ID_taller { get; set; }
        public Nullable<int> RNC { get; set; }
        public string Nombre_taller { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<SYSTAS_FACTURA> SYSTAS_FACTURA { get; set; }
    }
}
