//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTA_SERVICIO
    {
        public int id_servicio { get; set; }
        public string nombre_servicio { get; set; }
        public string tipo_servicio { get; set; }
        public Nullable<double> costo { get; set; }
    }
}
