//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTA_MECANICO
    {
        public int ID_Mecanico { get; set; }
        public string nombre_mecanico { get; set; }
        public string apellido_mecanico { get; set; }
        public string cedula_mecanico { get; set; }
        public string fecha_nac { get; set; }
        public Nullable<bool> Disponible { get; set; }
    }
}
