//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTA_DETALLE_REPARACION
    {
        public int ID_Detalle { get; set; }
        public string Estado_Vehiculo { get; set; }
        public string Piezas_usadas { get; set; }
        public string mecanico_asignado { get; set; }
        public Nullable<double> mano_obra { get; set; }
        public Nullable<double> precio_piezas { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
